# Generated by Django 3.2.8 on 2022-05-06 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TodoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=250)),
                ('task', models.TextField(blank=True)),
                ('date_started', models.DateField(default='2022-05-06')),
                ('due_date', models.DateField(default='2022-05-06')),
                ('category', models.ForeignKey(default='personal', on_delete=django.db.models.deletion.CASCADE, to='myTodoApp.category')),
            ],
            options={
                'ordering': ['-date_started'],
            },
        ),
    ]
